---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: true
  #chef_omnibus_url: https://www.chef.io/chef/install.sh

platforms:
  - name: centos/7
    driver:
      box: centos/7

suites:
  - name: default
    run_list: 
      - recipe[node-test::default]
    attributes:
    driver:
      synced_folders: 
        - ['../share', '/home/vagrant/share']
      network:
        - ['private_network', {type: 'dhcp'}]
        - ['forwarded_port',  {guest: 80, host: 7777}]
