name             'node-test'
maintainer       'Fabrizio Catitti'
maintainer_email ''
license          'All rights reserved'
description      'Installs/Configures node-test'
long_description 'Installs/Configures node-test'
version          '0.1.0'

depends 'nginx', '~> 2.7.6'
depends 'nodejs', '~> 2.4.4'
